name: greet
on:
  push:
    branches:
      - master
  schedule:
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run onliner
        run: echo hello
