name: Angular GitHub CI
on:
  push:
    branches:
      - master
  schedule:
    - workflow_dispatch
jobs: 
  greet:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: say hello
        run: echo hello world!